spring.datasource.url= jdbc:postgresql://localhost:5432/ads-online
spring.datasource.username= ads_user
spring.datasource.password= Str0ngP@ssw0rd!2025

spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate