spring.datasource.url= jdbc:postgresql://localhost:5432/ads-online
spring.datasource.username= ads_user
spring.datasource.password= Str0ngP@ssw0rd!2025

spring.liquibase.change-log=classpath:db/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

upload.path=./uploads